version: "3.9"

services:
  db:
    image: mysql:8.1
    container_name: fora-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ:-Asia/Seoul}
    volumes:
      - db-data:/var/lib/mysql
    # prod DB는 보안그룹으로만 접근 허용 (포트 열 필요 없음)
    # ports:
    #   - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} --silent" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  db-data:
