version: "3.9"

services:
  db:
    image: mysql:8.1
    container_name: fora-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ:-Asia/Seoul}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} --silent" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fora-app
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: ${JAVA_OPTS}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${SERVER_PORT}/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db-data:
