spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  open-in-view: false
  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8080}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
