spring:
  profiles:
    active: local

spcde-info:
  service-key: "dhCJs0Hk87xeU6jKWLg1aOEjdX%2BmhaAxCezeT9NqSXQgKkXZmEBpihBbKecC97NMTFsIS6MS4xS%2B4OksX7gW6w%3D%3D"

---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
