spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database

security:
  jwt:
    token:
      secret-key: "ThisIsSecretKey1!2@3#4$5%ThisIsSecretKey1!2@3#4$5%ThisIsSecretKey1!2@3#4$5%ThisIsSecretKey1!2@3#4$5%"

spcde-info:
  service-key: "dhCJs0Hk87xeU6jKWLg1aOEjdX%2BmhaAxCezeT9NqSXQgKkXZmEBpihBbKecC97NMTFsIS6MS4xS%2B4OksX7gW6w%3D%3D"
