spring:
  datasource:
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE:fora_final_mission}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME:${MYSQL_USER:fora}}
    password: ${DB_PASSWORD:${MYSQL_PASSWORD:password}}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  open-in-view: false
  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8080}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
